// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjZmJIvim-raSN_HgNUXqRQPIaNIIKe4',
    appId: '1:941736627728:web:f2514a37c346f5b43ec495',
    messagingSenderId: '941736627728',
    projectId: 'task-management-apps-9337c',
    authDomain: 'task-management-apps-9337c.firebaseapp.com',
    storageBucket: 'task-management-apps-9337c.appspot.com',
    measurementId: 'G-8T2HBBTL91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAklB_G0lLu5e3KA-Yh4zUgdnCs-ysnXL8',
    appId: '1:941736627728:android:86947e3940434fa43ec495',
    messagingSenderId: '941736627728',
    projectId: 'task-management-apps-9337c',
    storageBucket: 'task-management-apps-9337c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnkE5byiyQRvVcUm7IeW04-g_jiZUy5N8',
    appId: '1:941736627728:ios:155d42ab0be96d3d3ec495',
    messagingSenderId: '941736627728',
    projectId: 'task-management-apps-9337c',
    storageBucket: 'task-management-apps-9337c.appspot.com',
    androidClientId: '941736627728-0fq5th7tdfve5g4mdh37vo84bki00usl.apps.googleusercontent.com',
    iosClientId: '941736627728-tiifca9c0ecup1k1uimsa4ot03shup16.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuis1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnkE5byiyQRvVcUm7IeW04-g_jiZUy5N8',
    appId: '1:941736627728:ios:155d42ab0be96d3d3ec495',
    messagingSenderId: '941736627728',
    projectId: 'task-management-apps-9337c',
    storageBucket: 'task-management-apps-9337c.appspot.com',
    androidClientId: '941736627728-0fq5th7tdfve5g4mdh37vo84bki00usl.apps.googleusercontent.com',
    iosClientId: '941736627728-tiifca9c0ecup1k1uimsa4ot03shup16.apps.googleusercontent.com',
    iosBundleId: 'com.example.kuis1',
  );
}
